services:
  auth-user-api:
    container_name: auth-user-api
    image: ghcr.io/bob-park/on-time-api
    build:
      dockerfile: ./Dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64